[build]
  command = "npm run build && prisma generate"
  functions = "lambda" 

[build.environment]
  NEXT_PRIVATE_TARGET = "your_next_private_target"

[build.environment]
  PRISMA_GENERATE = "true"

[build.environment]
  PRISMA_MIGRATE = "true"

NEXTAUTH_JWT_SECRET="supersecret"
NEXTAUTH_SECRET="supersecret"
MONOGO="mongodb+srv://seba:sebas@cluster0.yatljvf.mongodb.net/twitter"