[build]
  command = "npm run build && prisma generate"
  functions = "lambda" 

[build.environment]
  NEXT_PRIVATE_TARGET = "your_next_private_target"

[build.environment]
  PRISMA_GENERATE = "true"

[build.environment]
  PRISMA_MIGRATE = "true"

[build.environment]
NEXTAUTH_JWT_SECRET

[build.environment]
NEXTAUTH_SECRET

[build.environment]
MONOGO